### ISSUE TITLE
Update Bios P4.3 Settings & Catalina

### ISSUE THREAD

**Issue by Phenek** [SeonMe/ASRock-Hackintosh-OC#1]
Hello,
First thanks for your repo.
I am actually blocked with an issue on Bios P4.1 .
I was thinking about downgrade my Bios to make it work ,but there you come!

So you are on Bios P4.3 and it seems to work! Great :)))
Would it be possible that you push your saving Bios settings on the repository?
(On ASRock Bios, you can save the settings on external Hard drive it will be a .BIN extension)

**Comment by SeonMe** [comment]
> 您好，
> 首先感谢您的回购。
> 实际上，我因Bios P4.1的问题而受阻。
> 我当时正在考虑降级我的BIOS以使其正常运行，但是您来了！
> 
> 因此，您使用的是Bios P4.3，它似乎可以工作！太好了：)））
> 是否有可能将保存的Bios设置推送到存储库中？
> （在ASRock Bios上，您可以将设置保存在扩展名为.BIN的外部硬盘上）

Modify it according to the BIOS settings.:)

**Comment by SeonMe** [comment]
> Hello,
> First thanks for your repo.
> I am actually blocked with an issue on Bios P4.1 .
> I was thinking about downgrade my Bios to make it work ,but there you come!
> 
> So you are on Bios P4.3 and it seems to work! Great :)))
> Would it be possible that you push your saving Bios settings on the repository?
> (On ASRock Bios, you can save the settings on external Hard drive it will be a .BIN extension)

Modify it according to the BIOS settings. :)

**Comment by soulomoon** [comment]
I could not boot following the readme bois configuration P4.3 except could not find Execute Disable Bit option anywhere. 
Could you guys please share the bios configuration with me?

**Comment by soulomoon** [comment]
Got my computer to work now after messing around with bois 4.30
