### ISSUE TITLE
Fixing location-based services

### ISSUE THREAD

**Issue by sarkrui** [SeonMe/ASRock-Hackintosh-OC#2]
For the not working part as mentioned at [Not Works](https://github.com/SeonMe/ASRock-Z390M-Pro4-Hackintosh-OC#not-works), you could try: 
* Unlock MSR 
* Enable NVRAM
  * Solution 1: patched with [SSDT-PMC.dsl](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/AcpiSamples/SSDT-PMC.dsl), and [tutorial](https://www.reddit.com/r/hackintosh/comments/erd2th/nvram_for_all_300_series_users_rejoice/) for all z390 series (**recommended**!)
  * Solution 2: using `LogoutHook.command`, check [tutorial](https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/post-install/nvram)
_(Although I could have forked and pulled a request for your repository, I indeed would like you to know why it is.)_

**Comment by SeonMe** [comment]
> For the not working part as mentioned at [Not Works](https://github.com/SeonMe/ASRock-Z390M-Pro4-Hackintosh-OC#not-works), you could try:
> 
> * Unlock MSR
> * Enable NVRAM
>   
>   * Solution 1: patched with [SSDT-PMC.dsl](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/AcpiSamples/SSDT-PMC.dsl), and [tutorial](https://www.reddit.com/r/hackintosh/comments/erd2th/nvram_for_all_300_series_users_rejoice/) for all z390 series (**recommended**!)
>   * Solution 2: using `LogoutHook.command`, check [tutorial](https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/post-install/nvram)
>     _(Although I could have forked and pulled a request for your repository, I indeed would like you to know why it is.)_

It's the cause of my local wireless network, not a configuration issue, but thanks for your comments.
