### ISSUE TITLE
CPU Fan full loaded when booting

### ISSUE THREAD

**Issue by FotixChiang** [SeonMe/ASRock-Hackintosh-OC#4]
maybe last for ten seconds, with loud noise. is it because CPUfriend.kext?

**Comment by SeonMe** [comment]
> maybe last for ten seconds, with loud noise. is it because CPUfriend.kext?

This is the frequency conversion of the CPU and needs to be used. I do n’t know where you modified it?

**Comment by FotixChiang** [comment]
> This is the frequency conversion of the CPU and needs to be used. I do n’t know where you modified it?

I modified nothing. Just clone the whole zip in EFI. I will have a test for that.

**Comment by SeonMe** [comment]
> > This is the frequency conversion of the CPU and needs to be used. I do n’t know where you modified it?
> 
> I modified nothing. Just clone the whole zip in EFI. I will have a test for that.

Hey brothers, you need to make the corresponding changes to use.
