### ISSUE TITLE
Stuck at In Memory Panic Stackshot Succeeded

### ISSUE THREAD

**Issue by brokenbracelet** [SeonMe/ASRock-Hackintosh-OC#5]
I used your EFI folder and get that error. I'm using the same motherboard and my CPU is i7-8700 with RX580 GPU. The pci list seems same, so Inly changed the machine information.

Any idea?

**Comment by SeonMe** [comment]
> I used your EFI folder and get that error. I'm using the same motherboard and my CPU is i7-8700 with RX580 GPU. The pci list seems same, so Inly changed the machine information.
> 
> Any idea?

Maybe you can delete something in DeviceProperties and try again

**Comment by SeonMe** [comment]
> > I used your EFI folder and get that error. I'm using the same motherboard and my CPU is i7-8700 with RX580 GPU. The pci list seems same, so Inly changed the machine information.
> > Any idea?
> 
> Maybe you can delete something in DeviceProperties and try again

Oh, I know. My EFI is a modified version of WhateverGreen. You need to replace the original version, and you need to delete the DeviceProperties graphics card and delete the NVRAM part shikigva = 80. Please download the original version from here.

https://github.com/acidanthera/WhateverGreen

**Comment by brokenbracelet** [comment]
Thanks. Anyway I changed the things u mention but got kernel panic instead.
Lastly I build my own OpenCore EFI from the guide and successfully boot.

**Comment by SeonMe** [comment]
> Thanks. Anyway I changed the things u mention but got kernel panic instead.
> Lastly I build my own OpenCore EFI from the guide and successfully boot.

Cool, then you are really great.
