### ISSUE TITLE
in memory panic stackshot succeeded

### ISSUE THREAD

**Issue by shravan0308** [SeonMe/ASRock-Hackintosh-OC#6]
I am Facing That type of Problem... I can't Slove this problem...(in memory panic stackshot succeeded) please Guys help me.
![IMG-20200518-WA0004](https://user-images.githubusercontent.com/51925045/82246987-46641e80-9963-11ea-92da-97c86b108376.jpeg)

My Setup:
Intel i5 8600k 
Cosair 8gb ram 3000mhz
Gigabyte Z370 d3h Motherboard

**Comment by SeonMe** [comment]
> I am Facing That type of Problem... I can't Slove this problem...(in memory panic stackshot succeeded) please Guys help me.
> ![IMG-20200518-WA0004](https://user-images.githubusercontent.com/51925045/82246987-46641e80-9963-11ea-92da-97c86b108376.jpeg)
> 
> My Setup:
> Intel i5 8600k
> Cosair 8gb ram 3000mhz
> Gigabyte Z370 d3h Motherboard

Please find the EFI of the corresponding motherboard for installation.
